from enum import Enum, unique

@unique
class ErrorType(Enum):
    API_ERROR = "API_ERROR"
    DATABASE_ERROR = "DATABASE_ERROR"
    AUTHENTICATION_ERROR = "AUTHENTICATION_ERROR"
    DATA_VALIDATION_ERROR = "DATA_VALIDATION_ERROR"
    TIMEOUT_ERROR = "TIMEOUT_ERROR"
    RESOURCE_NOT_FOUND_ERROR = "RESOURCE_NOT_FOUND_ERROR"
    UNKNOWN_ERROR = "UNKNOWN_ERROR"
